server:
  port: 8811

spring:
  # Database
  datasource:
    url: jdbc:mysql://${rds.mysql.url}
    username: ${rds.mysql.username}
    password: ${rds.mysql.password}

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

    ## for debugging
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health, info, caches, metrics
