server:
  port: 8811

spring:
  # Pretty JSON Response
  jackson:
    serialization:
      INDENT_OUTPUT: true

  # Database
  datasource:
    url: jdbc:h2:mem:demo
    username: gngsn
    password: ${internal.h2.password}
    driverClassName: org.h2.Driver

  # H2
  h2:
    console:
      enabled: true
      path: /h2-console
      generateDdl: true

  # JPA
  jpa:
    database_platform: org.hibernate.dialect.H2Dialect
    defer_datasource_initialization: true

    ## for debugging
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

# Logging
logging:
  level:
    org:
      springframework.data.jpa: DEBUG
      hibernate.SQL: DEBUG
