INSERT INTO keyword (`word`, `hit`) VALUES ('유가네 닭갈비', 238);
INSERT INTO keyword (`word`, `hit`) VALUES ('커브스', 309);
INSERT INTO keyword (`word`, `hit`) VALUES ('깐깐한 족발', 59);
INSERT INTO keyword (`word`, `hit`) VALUES ('세븐스타코인노래연습장', 320);
INSERT INTO keyword (`word`, `hit`) VALUES ('이삭토스트', 116);
INSERT INTO keyword (`word`, `hit`) VALUES ('더진국', 114);
INSERT INTO keyword (`word`, `hit`) VALUES ('세븐스타코인 노래연습장', 64);
INSERT INTO keyword (`word`, `hit`) VALUES ('곽두리쪽갈비', 356);
INSERT INTO keyword (`word`, `hit`) VALUES ('마루회덮밥', 332);
INSERT INTO keyword (`word`, `hit`) VALUES ('개미인력개발', 297);
INSERT INTO keyword (`word`, `hit`) VALUES ('안경매니저', 404);
INSERT INTO keyword (`word`, `hit`) VALUES ('1인용', 34);
INSERT INTO keyword (`word`, `hit`) VALUES ('이비가짬뽕', 362);
INSERT INTO keyword (`word`, `hit`) VALUES ('수유리 우동집', 385);
INSERT INTO keyword (`word`, `hit`) VALUES ('꼬지사께', 74);
INSERT INTO keyword (`word`, `hit`) VALUES ('이화수 전통육개장', 297);
INSERT INTO keyword (`word`, `hit`) VALUES ('도이첸', 331);
INSERT INTO keyword (`word`, `hit`) VALUES ('한앤둘치킨', 482);
INSERT INTO keyword (`word`, `hit`) VALUES ('김형제고기의철학', 430);
INSERT INTO keyword (`word`, `hit`) VALUES ('피자', 192);
INSERT INTO keyword (`word`, `hit`) VALUES ('땅땅치킨', 300);
INSERT INTO keyword (`word`, `hit`) VALUES ('피자마루', 312);
INSERT INTO keyword (`word`, `hit`) VALUES ('못된 고양이', 61);
INSERT INTO keyword (`word`, `hit`) VALUES ('아소비', 150);
INSERT INTO keyword (`word`, `hit`) VALUES ('참이맛감자탕', 232);
INSERT INTO keyword (`word`, `hit`) VALUES ('이차돌', 423);
INSERT INTO keyword (`word`, `hit`) VALUES ('얌샘김밥', 246);
INSERT INTO keyword (`word`, `hit`) VALUES ('33떡볶이', 266);
INSERT INTO keyword (`word`, `hit`) VALUES ('메가 커피', 496);
INSERT INTO keyword (`word`, `hit`) VALUES ('카페앤루비', 445);
INSERT INTO keyword (`word`, `hit`) VALUES ('핸즈커피', 394);
INSERT INTO keyword (`word`, `hit`) VALUES ('반딧불이', 60);
INSERT INTO keyword (`word`, `hit`) VALUES ('오레시피', 163);
INSERT INTO keyword (`word`, `hit`) VALUES ('바보스', 328);
INSERT INTO keyword (`word`, `hit`) VALUES ('세븐스타코인노래방', 175);
INSERT INTO keyword (`word`, `hit`) VALUES ('엘리팝', 411);
INSERT INTO keyword (`word`, `hit`) VALUES ('에듀플렉스', 347);
INSERT INTO keyword (`word`, `hit`) VALUES ('자담치킨', 23);
INSERT INTO keyword (`word`, `hit`) VALUES ('티바두마리치킨', 96);
INSERT INTO keyword (`word`, `hit`) VALUES ('카페루앤비', 134);
INSERT INTO keyword (`word`, `hit`) VALUES ('한촌설렁탕', 497);
INSERT INTO keyword (`word`, `hit`) VALUES ('IGA 마트', 155);
INSERT INTO keyword (`word`, `hit`) VALUES ('이바돔 감자탕', 416);
INSERT INTO keyword (`word`, `hit`) VALUES ('푸라닭', 249);
INSERT INTO keyword (`word`, `hit`) VALUES ('깐깐한족발', 157);
INSERT INTO keyword (`word`, `hit`) VALUES ('크라운호프', 49);
INSERT INTO keyword (`word`, `hit`) VALUES ('맛깔참죽', 421);
INSERT INTO keyword (`word`, `hit`) VALUES ('메가엠지씨커피', 445);
INSERT INTO keyword (`word`, `hit`) VALUES ('할매손충무김밥', 481);
INSERT INTO keyword (`word`, `hit`) VALUES ('유가네닭갈비', 281);
INSERT INTO keyword (`word`, `hit`) VALUES ('참이맛 감자탕', 171);
INSERT INTO keyword (`word`, `hit`) VALUES ('커피베이', 454);
INSERT INTO keyword (`word`, `hit`) VALUES ('월드클리닝', 477);
INSERT INTO keyword (`word`, `hit`) VALUES ('요거프레소', 75);
INSERT INTO keyword (`word`, `hit`) VALUES ('바른치킨', 486);
INSERT INTO keyword (`word`, `hit`) VALUES ('시루향기', 38);
INSERT INTO keyword (`word`, `hit`) VALUES ('월드크리닝', 492);
INSERT INTO keyword (`word`, `hit`) VALUES ('소담애', 216);
INSERT INTO keyword (`word`, `hit`) VALUES ('할매손 충무김밥', 53);
INSERT INTO keyword (`word`, `hit`) VALUES ('용우동', 145);
INSERT INTO keyword (`word`, `hit`) VALUES ('에듀 플렉스', 291);
INSERT INTO keyword (`word`, `hit`) VALUES ('덤인', 393);
INSERT INTO keyword (`word`, `hit`) VALUES ('한마음정육식당', 118);
INSERT INTO keyword (`word`, `hit`) VALUES ('크린토피아', 263);
INSERT INTO keyword (`word`, `hit`) VALUES ('수유리우동집', 174);
INSERT INTO keyword (`word`, `hit`) VALUES ('토프레소', 134);
INSERT INTO keyword (`word`, `hit`) VALUES ('메가MGC커피', 204);
INSERT INTO keyword (`word`, `hit`) VALUES ('삼첩분식', 442);
INSERT INTO keyword (`word`, `hit`) VALUES ('멕시카나', 111);
INSERT INTO keyword (`word`, `hit`) VALUES ('맘스터치', 708);
INSERT INTO keyword (`word`, `hit`) VALUES ('정직유부', 187);
INSERT INTO keyword (`word`, `hit`) VALUES ('신전떡복이', 716);
INSERT INTO keyword (`word`, `hit`) VALUES ('네네치킨', 826);
INSERT INTO keyword (`word`, `hit`) VALUES ('배스킨라빈스', 509);
INSERT INTO keyword (`word`, `hit`) VALUES ('자담치킨', 692);
INSERT INTO keyword (`word`, `hit`) VALUES ('벌크커피(BULK COFFEE)', 118);
INSERT INTO keyword (`word`, `hit`) VALUES ('미카도스시', 276);
INSERT INTO keyword (`word`, `hit`) VALUES ('군자대한곱창', 538);
INSERT INTO keyword (`word`, `hit`) VALUES ('서가앤쿡', 527);
INSERT INTO keyword (`word`, `hit`) VALUES ('불닭발땡초동대문엽기떡볶이', 31);
INSERT INTO keyword (`word`, `hit`) VALUES ('60계', 793);
INSERT INTO keyword (`word`, `hit`) VALUES ('치킨더홈', 570);
INSERT INTO keyword (`word`, `hit`) VALUES ('페리카나', 237);
INSERT INTO keyword (`word`, `hit`) VALUES ('매머드익스프레스(Mammoth Express)', 107);
INSERT INTO keyword (`word`, `hit`) VALUES ('땅스부대찌개', 756);
INSERT INTO keyword (`word`, `hit`) VALUES ('써브웨이(Subway)', 171);
INSERT INTO keyword (`word`, `hit`) VALUES ('인생극장', 734);
INSERT INTO keyword (`word`, `hit`) VALUES ('설동궁찜닭', 908);
INSERT INTO keyword (`word`, `hit`) VALUES ('미소야', 817);
INSERT INTO keyword (`word`, `hit`) VALUES ('본도시락', 27);
INSERT INTO keyword (`word`, `hit`) VALUES ('설빙', 147);
INSERT INTO keyword (`word`, `hit`) VALUES ('노브랜드 버거(No Brand Burger)', 952);
INSERT INTO keyword (`word`, `hit`) VALUES ('짬뽕지존', 183);
INSERT INTO keyword (`word`, `hit`) VALUES ('육대장', 719);
INSERT INTO keyword (`word`, `hit`) VALUES ('인생닭강정', 594);
INSERT INTO keyword (`word`, `hit`) VALUES ('맛찬들왕소금구이', 823);
INSERT INTO keyword (`word`, `hit`) VALUES ('피자마루', 452);
INSERT INTO keyword (`word`, `hit`) VALUES ('닥엔돈스', 403);
INSERT INTO keyword (`word`, `hit`) VALUES ('본죽&비빔밥', 994);
INSERT INTO keyword (`word`, `hit`) VALUES ('카페051 (cafe051)', 307);
INSERT INTO keyword (`word`, `hit`) VALUES ('세광양대창', 928);
INSERT INTO keyword (`word`, `hit`) VALUES ('던킨/던킨도너츠', 306);
INSERT INTO keyword (`word`, `hit`) VALUES ('오복오봉집', 806);
INSERT INTO keyword (`word`, `hit`) VALUES ('KFC', 640);
INSERT INTO keyword (`word`, `hit`) VALUES ('고기듬뿍 대왕비빔밥', 635);
INSERT INTO keyword (`word`, `hit`) VALUES ('더벤티', 443);
INSERT INTO keyword (`word`, `hit`) VALUES ('국제통닭', 663);
INSERT INTO keyword (`word`, `hit`) VALUES ('이비가짬뽕', 984);
INSERT INTO keyword (`word`, `hit`) VALUES ('송주불냉면앤칼국수', 754);
INSERT INTO keyword (`word`, `hit`) VALUES ('핵밥', 716);
INSERT INTO keyword (`word`, `hit`) VALUES ('웅이네 오돌뼈', 680);
INSERT INTO keyword (`word`, `hit`) VALUES ('빽다방', 289);
INSERT INTO keyword (`word`, `hit`) VALUES ('채선당도시락&샐러드', 449);
INSERT INTO keyword (`word`, `hit`) VALUES ('하남돼지집', 797);
INSERT INTO keyword (`word`, `hit`) VALUES ('컴포즈커피(COMPOSE COFFEE)', 761);
INSERT INTO keyword (`word`, `hit`) VALUES ('수유리우동집', 380);
INSERT INTO keyword (`word`, `hit`) VALUES ('경양카츠', 23);
INSERT INTO keyword (`word`, `hit`) VALUES ('구구족', 233);
INSERT INTO keyword (`word`, `hit`) VALUES ('크리스피크림', 756);
INSERT INTO keyword (`word`, `hit`) VALUES ('우리할매 떡볶이', 487);
INSERT INTO keyword (`word`, `hit`) VALUES ('걸작떡볶이치킨', 396);
INSERT INTO keyword (`word`, `hit`) VALUES ('청년다방', 820);
INSERT INTO keyword (`word`, `hit`) VALUES ('족발야시장', 232);
INSERT INTO keyword (`word`, `hit`) VALUES ('정통집', 141);
INSERT INTO keyword (`word`, `hit`) VALUES ('더리터(THE LITER)', 313);
INSERT INTO keyword (`word`, `hit`) VALUES ('자가제빵 선명희피자', 560);
INSERT INTO keyword (`word`, `hit`) VALUES ('라라코스트(raracost)', 256);